[build]
  command = "npm run build"
  functions = "func/"
  publish = ""

  [dev]
  framework = "#custom"
  command = "npm run start:dev"
  functions = "func/"
  publish = ""
  targetPort = 3000

[[redirects]] 
  from = "/api/setEnv"
  to = "/.netlify/functions/setEnv"
  status = 200
